### PR TITLE
Typescript support

### LINKED ISSUE #1: Use typescript

### PR DESCRIPTION
**Pull request by rafaelgalani**
Fixes #1.

### CODE REVIEW

**Comment by ugopp** [comment]
I don't agree

**Comment by romulogmp** [comment]
Parameter 'request' implicitly has an 'any' type.
Parameter 'response' implicitly has an 'any' type.

**Comment by rafaelgalani** [comment]
> Parameter 'request' implicitly has an 'any' type.
> Parameter 'response' implicitly has an 'any' type.

Could you share your linter config? It looks fine here: 

image

**Pull request merged**
